version: '3'
services:
  python:
    build: .
    container_name: python
    volumes:
      - ./app:/opt/app
    entrypoint: /bin/bash -c "pip freeze > /opt/app/requirements/requirements.txt"
    